# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envirou < Formula
  desc "View and manage your shell environment variables"
  homepage "https://github.com/sverrirab/envirou"
  version "5.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.3/envirou_5.3.3_darwin_amd64.tar.gz"
      sha256 "f9762cc851ca60034f5e7da9f8b68fdbb89c3841d716c036afdbce90a1151f7f"

      define_method(:install) do
        bin.install "envirou"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.3/envirou_5.3.3_darwin_arm64.tar.gz"
      sha256 "0efe923cedc870265c6301b2af3cdb1990e03aa1ce992aca17bf6abc8c18e948"

      define_method(:install) do
        bin.install "envirou"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.3/envirou_5.3.3_linux_amd64.tar.gz"
      sha256 "bffa06daa795462fbc175f7625e20316c07a22052cea13d1eaa7dcb1036daba2"
      define_method(:install) do
        bin.install "envirou"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.3/envirou_5.3.3_linux_arm64.tar.gz"
      sha256 "950bcc260a4ca70ebd3b6bb1ce3cebd4a0019e5e5c6435f0bc76b93895d03c3d"
      define_method(:install) do
        bin.install "envirou"
      end
    end
  end

  test do
    system "#{bin}/envirou", "version"
  end
end
