# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envirou < Formula
  desc "View and manage your shell environment variables"
  homepage "https://github.com/sverrirab/envirou"
  version "5.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.0/envirou_5.3.0_darwin_amd64.tar.gz"
      sha256 "9f5e2de84ea03e72b3ce719b6914abef620221e1d33404c3613874c1c7073ef3"

      define_method(:install) do
        bin.install "envirou"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.0/envirou_5.3.0_darwin_arm64.tar.gz"
      sha256 "be306fddd416ce6e446cbaf092305ba1e94dc15723a1f4f5c4c9c475c049aa49"

      define_method(:install) do
        bin.install "envirou"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.0/envirou_5.3.0_linux_amd64.tar.gz"
      sha256 "aec36a1a4d7b63ddd0e57a4e572ebceaca9b6b2b2750fcbe1baff7412320c4e6"
      define_method(:install) do
        bin.install "envirou"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sverrirab/envirou/releases/download/v5.3.0/envirou_5.3.0_linux_arm64.tar.gz"
      sha256 "1f88e3565da7f41505e4c3666284633bcd0e7cdc9374237155fe84d10050a124"
      define_method(:install) do
        bin.install "envirou"
      end
    end
  end

  test do
    system "#{bin}/envirou", "version"
  end
end
